stages:
 - afs_pull

afs:
  stage: afs_pull
  image: gitlab-registry.cern.ch/acc-models/acc-models-www/cern_cc7_base
  before_script:
    - mkdir -p ~/.ssh
    - 'echo "lxplus ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDTA/5AzXgbkSapknIPDoEePTM1PzIBSiyDnpZihdDXKzm8UdXxCDJLUVjBwc1JfBjnaXPEeBKZDuozDss/m98m5qQu+s2Dks000V8cUFTU+BFotzRWX0jWSBpmzse0477b40X2XCPqX0Cqfx9yHdkuMlyF0kJRxXgsGTcwzwbmvqNHJdHHYJJz93hGpBhYMREcDN5VOxXz6Ack3X7xfF29xaC91oOAqq75O11LXF5Y4kAeN9kDG8o6Zsqk4c5at5aqWqzZfnnVtGjhkgU2Mt5aKwptaFMe0Z3ys/zZM4SnsE9NfompnnWsiKk2y09UvrbzuYPWLt43Fp3+IFqRJvBX" > ~/.ssh/known_hosts'
    - 'echo -e "Host *\n\tGSSAPIDelegateCredentials yes\n\tGSSAPITrustDNS yes\n\n" > ~/.ssh/config'
  script:
      - echo "${EOS_ACCOUNT_PASSWORD}" | kinit -f ${EOS_ACCOUNT_USERNAME}@CERN.CH
      - klist
      - ssh ${EOS_ACCOUNT_USERNAME}@lxplus "cd /afs/cern.ch/eng/acc-models/sps/${CI_COMMIT_REF_NAME}/;git pull"
      - ssh ${EOS_ACCOUNT_USERNAME}@lxplus "cd /eos/project/a/acc-models/public/sps/${CI_COMMIT_REF_NAME}/;git pull"

